version: "3.8"

services:
  app:
    build: .
    ports:
      - "3005:3005"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: > 
      bash -c "npm install 
      && npx nodemon index.js"
    